sqoop job --create CustomerJob \
  --import \
  --connect jdbc:mysql://localhost:3306/retail_db \
  --username root \
  --password ****** \
  --table customers \
  --check-column customer_id \
  --incremental append \
  --last-value 0 \
  --as-textfile \
  --warehouse-dir= /user/cloudera/sqoop_imported_tables/Cust
